# Generated by Django 5.1.6 on 2025-02-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='noname@null.com', max_length=320),
            preserve_default=False,
        ),
    ]
